FLASK_APP=run.py
FLASK_ENV=development
FLASK_CONFIGURATION=dev
SECRET_KEY=secret-key
FLASK_DEBUG=1

MASTER_MYSQL_DATABASE_USER = 'root'
MASTER_MYSQL_DATABASE_PASSWORD = 'password'
MASTER_MYSQL_DATABASE_HOST = 'localhost'
MASTER_MYSQL_DATABASE_DB_CASAONE = 'casaone'
