"""Initial migration.

Revision ID: 6fb7b1607a9b
Revises: 
Create Date: 2021-07-06 14:33:21.783553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fb7b1607a9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('product_id', 'order_id')
    )
    op.drop_table('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('product_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', 'order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ratings')
    # ### end Alembic commands ###
